minecraft_version: "26.1"
minecraft_download_url: "https://piston-data.mojang.com/v1/objects/3872a7f07a1a595e651aef8b058dfc2bb3772f46/server.jar"
minecraft_dir: "/opt/minecraft"
minecraft_server_dir: "/opt/minecraft/server"
minecraft_user: "minecraft"
minecraft_group: "minecraft"
minecraft_data_device: "/dev/nvme1n1"
java_xmx: "4G"
java_xms: "2G"